[package]
name = 'SeaInit'
version = '0.1.0'

[addresses]
sea = "0x393a63f47da7a757a252cb44fbab2afe602efe9d88e8ae84aac7db4949a9beb0"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
subdir = "aptos-move/framework/aptos-framework"
# rev = "563e2abff8fa997aec81abe48772af8a20731f76"
rev = "main"
